apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-comfyui
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
spec:
  project: default
  source:
    repoURL: https://github.com/lfoss0612/homelab-gitops.git
    targetRevision: HEAD
    path: argocd/comfyui
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
