apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: system
  source:
    chart: rancher
    helm:
      parameters:
        - name: ingress.ingressClassName
          value: nginx
        - name: replicas
          value: "1"
        - name: ingress.tls.secretName
          value: rancher-cert
        - name: hostname
          value: rancher.home.lan
    repoURL: https://releases.rancher.com/server-charts/latest
    targetRevision: 2.13.0
