apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: system
  source:
    chart: system-upgrade-controller
    helm:
      parameters:
        - name: global.cattle.systemDefaultRegistry
          value: ""
        - name: priorityClassName
          value: rancher-critical
    repoURL: https://charts.rancher.io
    targetRevision: 109.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
