{
 "title": "YugabyteDB",
 "description": "Note: It is recommended to use https://github.com/yugabyte/yugabyte-db/tree/master/cloud/grafana instead, this dashboard is out of date.\r\n\r\n\r\nYugabyteDB is the open source, distributed SQL database for global, internet-scale applications with low query latency, extreme resilience against failures.\r\n",
 "tags": [
  "YugabyteDB",
  "yugabytedb",
  "ysql",
  "ycql",
  "yedis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "dbcluster", "label": "YB DB Cluster", "query": "label_values(job)" },
   {
    "name": "node",
    "query": "label_values(up{job=\"$dbcluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"$dbcluster\"})"
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "avg(threads_running{job=\"$dbcluster\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "avg(threads_started{job=\"$dbcluster\"})",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "Master Log Ops / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_sync_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Sync"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_group_commit_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Commit"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_append_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg  - Append"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_sync_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Sync"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_group_commit_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Commit"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_append_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Append"
      }
     ]
    },
    {
     "title": "Master Log Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(irate(log_sync_latency_sum{job=\"$dbcluster\"}[5m])) / avg(irate(log_sync_latency_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Sync"
      },
      {
       "expr": "avg(irate(log_group_commit_latency_sum{job=\"$dbcluster\"}[5m])) / avg(irate(log_group_commit_latency_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Commit"
      },
      {
       "expr": "avg(irate(log_append_latency_sum{job=\"$dbcluster\"}[5m])) / avg(irate(log_append_latency_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Append"
      }
     ]
    },
    {
     "title": "Log Stats / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (log_reader_bytes_read{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "Total Avg - Log Bytes Read"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (log_cache_size{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "Total Avg - Log Cache Size"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_reader_bytes_read{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "{{exported_instance}} - Log Bytes Read"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_size{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "{{exported_instance}} - Log Cache Size"
      }
     ]
    },
    {
     "title": "Log Bytes Written / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_bytes_logged{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Log Bytes Logged"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_bytes_logged{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Log Bytes Logged"
      }
     ]
    },
    {
     "title": "Glog messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(glog_info_messages{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Info"
      },
      {
       "expr": "sum(rate(glog_warning_messages{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Warning"
      },
      {
       "expr": "sum(rate(glog_error_messages{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Log Bytes Read / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_reader_bytes_read{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Log Bytes Read"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_reader_bytes_read{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Log Bytes Read"
      }
     ]
    },
    {
     "title": "RPC queue sizes (Master)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "max(rpcs_in_queue_yb_master_MasterService{job=\"$dbcluster\"})",
       "legendFormat": "Master RPC"
      }
     ]
    },
    {
     "title": "Log Cache Num Ops / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (log_cache_num_ops{job=\"$dbcluster\"}))",
       "legendFormat": "Total Avg - Num Ops"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_num_ops{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "{{exported_instance}} - Num Ops"
      }
     ]
    },
    {
     "title": "Total Ops / Sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(irate(handler_latency_yb_tserver_TabletServerService_Write_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(irate(handler_latency_yb_tserver_TabletServerService_Read_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Op / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Write_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Write_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}} - Write"
      },
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Read_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Read_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}} - Read"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_tserver_TabletServerService_Read_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_tserver_TabletServerService_Read_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(irate(handler_latency_yb_tserver_TabletServerService_Write_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_tserver_TabletServerService_Write_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Reactor Delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "avg(irate(rpc_incoming_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incoming Queue"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_transfer_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound transfer time"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound queue time"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablet Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_tserver_TabletServerService_Read_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_tserver_TabletServerService_Read_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(irate(handler_latency_yb_tserver_TabletServerService_Write_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_tserver_TabletServerService_Write_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Reactor Delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "avg(irate(rpc_incoming_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incoming Queue"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_transfer_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound transfer time"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound queue time"
      }
     ]
    },
    {
     "title": "Total Ops / Sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(irate(handler_latency_yb_tserver_TabletServerService_Write_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(irate(handler_latency_yb_tserver_TabletServerService_Read_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Op / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Write_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Write_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}} - Write"
      },
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Read_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_tserver_TabletServerService_Read_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}} - Read"
      }
     ]
    },
    {
     "title": "Consensus Ops / Sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_consensus_ConsensusService_UpdateConsensus_sum{job=\"$dbcluster\"}[5m])) / sum(rate(handler_latency_yb_consensus_ConsensusService_UpdateConsensus_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "UpdateConsensus"
      },
      {
       "expr": "sum(rate(handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_sum{job=\"$dbcluster\"}[5m])) / sum(rate(handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "RequestConsensusVote"
      }
     ]
    },
    {
     "title": "Total Consensus Change Config",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(handler_latency_yb_consensus_ConsensusService_ChangeConfig{job=\"$dbcluster\"})",
       "legendFormat": "ChangeConfig"
      },
      {
       "expr": "sum(handler_latency_yb_consensus_ConsensusService_RunLeaderElection{job=\"$dbcluster\"})",
       "legendFormat": "RunLeaderElection"
      },
      {
       "expr": "sum(handler_latency_yb_consensus_ConsensusService_LeaderStepDown{job=\"$dbcluster\"})",
       "legendFormat": "LeaderStepDown"
      },
      {
       "expr": "sum(handler_latency_yb_consensus_ConsensusService_LeaderElectionLost{job=\"$dbcluster\"})",
       "legendFormat": "LeaderElectionLost"
      }
     ]
    },
    {
     "title": "Remote Bootstraps",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(handler_latency_yb_consensus_ConsensusService_StartRemoteBootstrap{job=\"$dbcluster\"})",
       "legendFormat": "remote bootstraps"
      }
     ]
    },
    {
     "title": "Consensus Rpc Latencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_consensus_ConsensusService_UpdateConsensus_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_consensus_ConsensusService_UpdateConsensus_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "UpdateConsensus"
      },
      {
       "expr": "avg(irate(handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "RequestConsensusVote"
      }
     ]
    },
    {
     "title": "Change Config Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_consensus_ConsensusService_ChangeConfig_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_consensus_ConsensusService_ChangeConfig_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "ChangeConfig"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "avg(threads_running{job=\"$dbcluster\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "avg(threads_started{job=\"$dbcluster\"})",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "avg(irate(involuntary_context_switches{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Involuntary"
      },
      {
       "expr": "avg(irate(voluntary_context_switches{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Voluntary"
      }
     ]
    },
    {
     "title": "SpinLock Time/Server",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "avg(rate(spinlock_contention_time{job=\"$dbcluster\"}[5m])) / 1000000",
       "legendFormat": "SpinLock"
      }
     ]
    },
    {
     "title": "TServer Log Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "avg(irate(log_sync_latency_sum{job=\"$dbcluster\"}[5m])) / avg(irate(log_sync_latency_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Sync"
      },
      {
       "expr": "avg(irate(log_group_commit_latency_sum{job=\"$dbcluster\"}[5m])) / avg(irate(log_group_commit_latency_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Commit"
      },
      {
       "expr": "avg(irate(log_append_latency_sum{job=\"$dbcluster\"}[5m])) / avg(irate(log_append_latency_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Append"
      }
     ]
    },
    {
     "title": "Log Bytes Written / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_bytes_logged{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Log Bytes Logged"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_bytes_logged{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Log Bytes Logged"
      }
     ]
    },
    {
     "title": "Log Bytes Read / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_reader_bytes_read{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Log Bytes Read"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_reader_bytes_read{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Log Bytes Read"
      }
     ]
    },
    {
     "title": "TServer Log Ops / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_sync_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Sync"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_group_commit_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg - Commit"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(log_append_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Total Avg  - Append"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_sync_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Sync"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_group_commit_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Commit"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_append_latency_count{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "{{exported_instance}} - Append"
      }
     ]
    },
    {
     "title": "TServer TCMalloc Stats",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "avg(generic_current_allocated_bytes{job=\"$dbcluster\"}) / 1048576",
       "legendFormat": "In Use"
      },
      {
       "expr": "avg(generic_heap_size{job=\"$dbcluster\"}) / 1048576",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Log Stats / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (log_reader_bytes_read{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "Total Avg - Log Bytes Read"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (log_cache_size{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "Total Avg - Log Cache Size"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_reader_bytes_read{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "{{exported_instance}} - Log Bytes Read"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_size{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "{{exported_instance}} - Log Cache Size"
      }
     ]
    },
    {
     "title": "Log Cache Num Ops / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (log_cache_num_ops{job=\"$dbcluster\"}))",
       "legendFormat": "Total Avg - Num Ops"
      },
      {
       "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_num_ops{job=\"$dbcluster\"})) / 1024",
       "legendFormat": "{{exported_instance}} - Num Ops"
      }
     ]
    },
    {
     "title": "Glog messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "sum(rate(glog_info_messages{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Info"
      },
      {
       "expr": "sum(rate(glog_warning_messages{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Warning"
      },
      {
       "expr": "sum(rate(glog_error_messages{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "RPC queue sizes (Tserver)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "max(rpcs_in_queue_yb_consensus_ConsensusService{job=\"$dbcluster\"})",
       "legendFormat": "Consensus"
      },
      {
       "expr": "max(rpcs_in_queue_yb_server_GenericService{job=\"$dbcluster\"})",
       "legendFormat": "Generic"
      },
      {
       "expr": "max(rpcs_in_queue_yb_tserver_RemoteBootstrapService{job=\"$dbcluster\"})",
       "legendFormat": "RemoteBootstrap"
      },
      {
       "expr": "max(rpcs_in_queue_yb_tserver_TabletServerService{job=\"$dbcluster\"})",
       "legendFormat": "TS RPC"
      },
      {
       "expr": "max(rpcs_in_queue_yb_tserver_TabletServerBackupService{job=\"$dbcluster\"})",
       "legendFormat": "Backups"
      },
      {
       "expr": "max(rpcs_in_queue_yb_tserver_TabletServerAdminService{job=\"$dbcluster\"})",
       "legendFormat": "Admin"
      },
      {
       "expr": "max(rpcs_in_queue_yb_cdc_CDCService{job=\"$dbcluster\"})",
       "legendFormat": "CDC"
      }
     ]
    }
   ]
  },
  {
   "title": "YEDIS Ops & Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total YEDIS Ops / Sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_get_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Get"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_mget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_exists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Exists"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_getrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetRange"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_set_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Set"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_mset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_getset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_append_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Append"
      },
      {
       "expr": " sum(rate(handler_latency_yb_redisserver_RedisServerService_del_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Del"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_setrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SetRange"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_incr_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incr"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsget_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsAdd"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsRangeByTime"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsrem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsRem"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_smembers_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SMembers"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_sismember_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SIsMember"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_scard_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SCard"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "StrLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_sadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SAdd"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_srem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SRem"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_echo_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Echo"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_auth_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Auth"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_config_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Config"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_info_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Info"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_role_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Role"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_ping_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Ping"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_quit_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Quit"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_flushdb_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "FlushDB"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_command_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Command"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hmget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hgetall_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGetAll"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hkeys_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HKeys"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hvals_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HVals"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hexists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HExists"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hstrlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HStrLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hmset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hdel_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HDel"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hincrby_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HIncrBy"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_get_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_get_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Get"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_mget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_mget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_exists_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_exists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Exists"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_getrange_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_getrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetRange"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_set_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_set_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Set"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_mset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_mset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_getset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_getset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_append_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_append_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Append"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_del_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_del_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Del"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_setrange_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_setrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SetRange"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_incr_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_incr_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incr"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsget_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsadd_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsAdd"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrangebytime_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsRangeByTime"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrem_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsRem"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_smembers_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_smembers_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SMembers"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_sismember_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_sismember_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SIsMember"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_scard_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_scard_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SCard"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "StrLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_sadd_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_sadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SAdd"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_srem_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_srem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SRem"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_echo_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_echo_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Echo"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_auth_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_auth_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Auth"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_config_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_config_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Config"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_info_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_info_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Info"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_role_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_role_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Role"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_ping_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_ping_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Ping"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_quit_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_quit_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Quit"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_flushdb_sum{job=\"$dbcluster\"}[5m])) /avg(rate(handler_latency_yb_redisserver_RedisServerService_flushdb_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "FlushDB"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_command_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_command_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Command"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hmget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hmget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hgetall_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hgetall_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGetAll"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hkeys_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hkeys_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HKeys"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hvals_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hvals_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HVals"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hexists_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hexists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HExists"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hstrlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hstrlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HStrLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hmset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hmset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hdel_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hdel_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HDel"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hincrby_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hincrby_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HIncrBy"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency (P95)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_get{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "Get"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_mget{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "MGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_strlen{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_exists{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Exists"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_getrange{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "GetRange"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_set{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Set"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_mset{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "MSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_getset{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "GetSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_append{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Append"
      },
      {
       "expr": " max(handler_latency_yb_redisserver_RedisServerService_del{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Del"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_setrange{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "SetRange"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_incr{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Incr"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsget{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "TsGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsadd{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "TsAdd"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsrangebytime{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "TsRangeByTime"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsrem{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "TsRem"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_smembers{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "SMembers"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_sismember{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "SIsMember"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_scard{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "SCard"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_strlen{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "StrLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_sadd{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "SAdd"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_srem{job=\"$dbcluster\",quantile=\"p95\"})",
       "legendFormat": "SRem"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_echo{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Echo"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_auth{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Auth"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_config{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Config"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_info{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Info"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_role{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Role"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_ping{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Ping"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_quit{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Quit"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_flushdb{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "FlushDB"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_command{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "Command"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hget{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hmget{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HMGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hgetall{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HGetAll"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hkeys{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HKeys"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hvals{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HVals"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hlen{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hexists{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HExists"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hstrlen{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HStrLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hset{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hmset{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HMSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hdel{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HDel"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hincrby{job=\"$dbcluster\",quantile=\"p95\"})\r",
       "legendFormat": "HIncrBy"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_get{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "Get"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_mget{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "MGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_strlen{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_exists{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Exists"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_getrange{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "GetRange"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_set{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Set"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_mset{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "MSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_getset{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "GetSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_append{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Append"
      },
      {
       "expr": " max(handler_latency_yb_redisserver_RedisServerService_del{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Del"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_setrange{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "SetRange"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_incr{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Incr"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsget{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "TsGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsadd{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "TsAdd"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsrangebytime{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "TsRangeByTime"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_tsrem{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "TsRem"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_smembers{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "SMembers"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_sismember{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "SIsMember"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_scard{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "SCard"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_strlen{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "StrLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_sadd{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "SAdd"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_srem{job=\"$dbcluster\",quantile=\"p99\"})",
       "legendFormat": "SRem"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_echo{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Echo"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_auth{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Auth"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_config{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Config"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_info{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Info"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_role{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Role"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_ping{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Ping"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_quit{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Quit"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_flushdb{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "FlushDB"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_command{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "Command"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hget{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hmget{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HMGet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hgetall{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HGetAll"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hkeys{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HKeys"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hvals{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HVals"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hlen{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hexists{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HExists"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hstrlen{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HStrLen"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hset{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hmset{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HMSet"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hdel{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HDel"
      },
      {
       "expr": "max(handler_latency_yb_redisserver_RedisServerService_hincrby{job=\"$dbcluster\",quantile=\"p99\"})\r",
       "legendFormat": "HIncrBy"
      }
     ]
    },
    {
     "title": "Total YEDIS Ops / Sec -- Hash",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hmget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hgetall_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGetAll"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hkeys_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HKeys"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hvals_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HVals"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hexists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HExists"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hstrlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HStrLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hmset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hdel_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HDel"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_hincrby_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HIncrBy"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency -- Hash",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hmget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hmget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hgetall_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hgetall_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HGetAll"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hkeys_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hkeys_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HKeys"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hvals_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hvals_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HVals"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hexists_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hexists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HExists"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hstrlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hstrlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HStrLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hmset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hmset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HMSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hdel_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hdel_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HDel"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_hincrby_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_hincrby_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "HIncrBy"
      }
     ]
    },
    {
     "title": "Total YEDIS Ops / Sec -- TS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsget_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsAdd"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsRangeByTime"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_tsrem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "TsRem"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency -- TS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "TsGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsadd_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsadd_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "TsAdd"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrangebytime_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "TsRangeByTime"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrem_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_tsrem_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "TsRem"
      }
     ]
    },
    {
     "title": "Total YEDIS Ops / Sec -- Set",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_smembers_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SMembers"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_sismember_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SIsMember"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_scard_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SCard"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "StrLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_sadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SAdd"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_srem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "SRem"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency -- Set",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_smembers_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_smembers_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SMembers"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_sismember_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_sismember_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SIsMember"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_scard_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_scard_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SCard"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_sadd_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_sadd_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SAdd"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_srem_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_srem_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SRem"
      }
     ]
    },
    {
     "title": "Total YEDIS Ops / Sec -- Sorted Set",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_zadd_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "ZAdd"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_zrem_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "ZRem"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_zcard_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "ZCard"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_zrevrange_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "ZRangeByScore"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_zrangebyscore_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "ZRevRange"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency -- Sorted Set",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_zadd_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_zadd_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "ZAdd"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_zrem_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_zrem_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "ZRem"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_zcard_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_zcard_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "ZCard"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_zrevrange_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_zrevrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "ZRevRange"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_zrangebyscore_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_zrangebyscore_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "ZRangeByScore"
      }
     ]
    },
    {
     "title": "Total YEDIS Ops / Sec -- Str",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_get_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Get"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_mget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MGet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_exists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Exists"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_getrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetRange"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_set_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Set"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_mset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_getset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetSet"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_append_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Append"
      },
      {
       "expr": " sum(rate(handler_latency_yb_redisserver_RedisServerService_del_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Del"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_setrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SetRange"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_incr_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incr"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency -- Str",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_get_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_get_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Get"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_mget_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_mget_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MGet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_strlen_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "StrLen"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_exists_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_exists_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Exists"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_getrange_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_getrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetRange"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_set_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_set_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Set"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_mset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_mset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "MSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_getset_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_getset_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "GetSet"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_append_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_append_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Append"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_del_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_del_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Del"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_setrange_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_setrange_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "SetRange"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_incr_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_incr_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incr"
      }
     ]
    },
    {
     "title": "Total YEDIS Ops / Sec -- Others",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_echo_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Echo"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_auth_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Auth"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_config_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Config"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_info_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Info"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_role_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Role"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_ping_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Ping"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_quit_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Quit"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_flushdb_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "FlushDB"
      },
      {
       "expr": "sum(rate(handler_latency_yb_redisserver_RedisServerService_command_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Command"
      }
     ]
    },
    {
     "title": "YEDIS Op Latency -- Others",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_echo_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_echo_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Echo"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_auth_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_auth_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Auth"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_config_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_config_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Config"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_info_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_info_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Info"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_role_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_role_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Role"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_ping_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_ping_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Ping"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_quit_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_quit_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Quit"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_flushdb_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_flushdb_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "FlushDB"
      },
      {
       "expr": "avg(rate(handler_latency_yb_redisserver_RedisServerService_command_sum{job=\"$dbcluster\"}[5m])) / avg(rate(handler_latency_yb_redisserver_RedisServerService_command_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Command"
      }
     ]
    },
    {
     "title": "RPC queue sizes (YEDIS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "max(rpcs_in_queue_yb_redisserver_RedisServerService{job=\"$dbcluster\"})",
       "legendFormat": "YEDIS RPC - Max"
      },
      {
       "expr": "rpcs_in_queue_yb_redisserver_RedisServerService{job=\"$dbcluster\"}",
       "legendFormat": "YEDIS RPC - {{exported_instance}}"
      }
     ]
    },
    {
     "title": "YBClient Reactor Delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "avg(irate(rpc_incoming_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incoming Queue"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_transfer_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound transfer time"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound queue time"
      }
     ]
    }
   ]
  },
  {
   "title": "YCQL Ops & Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total YCQL Ops / Sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Select"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Update"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Insert"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Other"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "YCQL Op Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Select"
      },
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Insert"
      },
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Update"
      },
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Other"
      },
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "YCQL Op Latency (P95)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt{job=\"$dbcluster\", quantile=\"p95\"})",
       "legendFormat": "Select"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt{job=\"$dbcluster\", quantile=\"p95\"})",
       "legendFormat": "Insert"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt{job=\"$dbcluster\", quantile=\"p95\"})",
       "legendFormat": "Update"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt{job=\"$dbcluster\", quantile=\"p95\"})",
       "legendFormat": "Delete"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts{job=\"$dbcluster\", quantile=\"p95\"})",
       "legendFormat": "Other"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_Transaction{job=\"$dbcluster\", quantile=\"p95\"})",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "YCQL Op Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt{job=\"$dbcluster\", quantile=\"p99\"})",
       "legendFormat": "Select"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt{job=\"$dbcluster\", quantile=\"p99\"})",
       "legendFormat": "Insert"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt{job=\"$dbcluster\", quantile=\"p99\"})",
       "legendFormat": "Update"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt{job=\"$dbcluster\", quantile=\"p99\"})",
       "legendFormat": "Delete"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts{job=\"$dbcluster\", quantile=\"p99\"})",
       "legendFormat": "Other"
      },
      {
       "expr": "max(handler_latency_yb_cqlserver_SQLProcessor_Transaction{job=\"$dbcluster\", quantile=\"p99\"})",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "Select - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Select - Op Latency (Avg) /  Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Update - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Update - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Delete - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Delete - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Insert - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Insert - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Others - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "repeat": "tserver",
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Others - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      },
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "Transaction - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Transaction - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_cqlserver_SQLProcessor_Transaction_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Reactor Delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "avg(irate(rpc_incoming_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Incoming Queue"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_transfer_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound transfer time"
      },
      {
       "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Outbound queue time"
      }
     ]
    },
    {
     "title": "YCQL Inbound Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "avg(irate(rpc_connections_alive{job=\"$dbcluster\",metric_id=\"yb.cqlserver\"}[5m]))",
       "legendFormat": "Connections Alive"
      }
     ]
    },
    {
     "title": "YCQL Latency Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_CQLServerService_ProcessRequest_sum{job=\"$dbcluster\"}[5m])) / sum(irate(handler_latency_yb_cqlserver_CQLServerService_ProcessRequest_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_CQLServerService_ParseRequest_sum{job=\"$dbcluster\"}[5m])) / sum(irate(handler_latency_yb_cqlserver_CQLServerService_ParseRequest_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Parse"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_CQLServerService_AnalyzeRequest_sum{job=\"$dbcluster\"}[5m])) / sum(irate(handler_latency_yb_cqlserver_CQLServerService_AnalyzeRequest_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Analyze"
      },
      {
       "expr": "sum(irate(handler_latency_yb_cqlserver_CQLServerService_ExecuteRequest_sum{job=\"$dbcluster\"}[5m])) / sum(irate(handler_latency_yb_cqlserver_CQLServerService_ExecuteRequest_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Execute"
      }
     ]
    },
    {
     "title": "Response Size (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_cqlserver_SQLProcessor_ResponseSize_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_cqlserver_SQLProcessor_ResponseSize_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Response Size"
      }
     ]
    },
    {
     "title": "RPC queue sizes (YCQL)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "max(rpcs_in_queue_yb_cqlserver_CQLServerService{job=\"$dbcluster\"})",
       "legendFormat": "YCQL RPC - Max"
      },
      {
       "expr": "rpcs_in_queue_yb_cqlserver_CQLServerService{job=\"$dbcluster\"}",
       "legendFormat": "YCQL RPC - {{exported_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "YSQL Ops & Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total YSQL Ops / Sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(irate(handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Select"
      },
      {
       "expr": "sum(irate(handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Update"
      },
      {
       "expr": "sum(irate(handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "sum(irate(handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Insert"
      },
      {
       "expr": "sum(irate(handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Other"
      },
      {
       "expr": "sum(irate(handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "YSQL Op Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Select"
      },
      {
       "expr": "avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Insert"
      },
      {
       "expr": "avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Update"
      },
      {
       "expr": "avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Other"
      },
      {
       "expr": "avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_Transactions_sum{job=\"$dbcluster\"}[5m])) / avg(irate(handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "Select - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Select - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "avg by (exported_instance)(irate(handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance)(irate(handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Insert - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Insert - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Update - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Update - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Delete - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Delete - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Others - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Others - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Transactions - Op / Sec / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count{job=\"$dbcluster\"}[5m]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Transactions - Op Latency (Avg) / Tserver",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_Transactions_sum{job=\"$dbcluster\"}[5m])) / avg by (exported_instance) (irate(handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count{job=\"$dbcluster\"}[5m]))\r",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "LSM-DB Seek/Next Num Ops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_number_db_seek{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Seek"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_number_db_next{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Next"
      }
     ]
    },
    {
     "title": "LSM-DB Seeks / Sec / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_number_db_seek{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Seek"
      }
     ]
    },
    {
     "title": "SSTable size / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rocksdb_total_sst_file_size{job=\"$dbcluster\"})) / 1073741824",
       "legendFormat": "Size of SSTables"
      }
     ]
    },
    {
     "title": "Average SSTables / Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rocksdb_current_version_num_sst_files{job=\"$dbcluster\"}))",
       "legendFormat": "Average SSTables / Node"
      }
     ]
    },
    {
     "title": "LSM-DB Blooms usefulness",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_bloom_filter_checked{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Blooms checked"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_bloom_filter_useful{job=\"$dbcluster\"}[5m]))) ",
       "legendFormat": "Blooms useful"
      }
     ]
    },
    {
     "title": "LSM-DB Get Latencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_get_micros_sum{job=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (rate(rocksdb_db_get_micros_count{job=\"$dbcluster\"}[5m]))\r)",
       "legendFormat": "Get"
      }
     ]
    },
    {
     "title": "LSM-DB Write Latencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_write_micros_sum{job=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (rate(rocksdb_db_write_micros_count{job=\"$dbcluster\"}[5m]))\r)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "LSM-DB Seek Latencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_seek_micros_sum{job=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (rate(rocksdb_db_seek_micros_count{job=\"$dbcluster\"}[5m]))\r)",
       "legendFormat": "Seek "
      }
     ]
    },
    {
     "title": "LSM-DB Mutex Wait Latencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_mutex_wait_micros{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Mutex"
      }
     ]
    },
    {
     "title": "Cache Hit & Miss",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_hit{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Hit"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_miss{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Miss"
      }
     ]
    },
    {
     "title": "Block cache usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "avg(block_cache_single_touch_usage{job=\"$dbcluster\"}) / 1073741824",
       "legendFormat": "Single Touch"
      },
      {
       "expr": "avg(block_cache_multi_touch_usage{job=\"$dbcluster\"}) / 1073741824",
       "legendFormat": "Multi Touch"
      }
     ]
    },
    {
     "title": "Cache Add",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_add{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Add"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_single_touch_add{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Single Touch Add"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_multi_touch_add{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Multi Touch Add"
      }
     ]
    },
    {
     "title": "Stalls",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_stall_micros{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Stalls"
      }
     ]
    },
    {
     "title": "Rejections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(majority_sst_files_rejections{job=\"$dbcluster\"}[5m])))",
       "legendFormat": "Rejections"
      }
     ]
    },
    {
     "title": "Flush write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_flush_write_bytes{job=\"$dbcluster\"}[5m]))) / 1048576",
       "legendFormat": "Flush"
      }
     ]
    },
    {
     "title": "Compaction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_compact_read_bytes{job=\"$dbcluster\"}[5m]))) / 1048576",
       "legendFormat": "Bytes Read"
      },
      {
       "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_compact_write_bytes{job=\"$dbcluster\"}[5m]))) / 1048576",
       "legendFormat": "Bytes Written"
      }
     ]
    },
    {
     "title": "Compaction num files",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (irate(rocksdb_numfiles_in_singlecompaction_sum{job=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (irate(rocksdb_numfiles_in_singlecompaction_count{job=\"$dbcluster\"}[5m]))\r)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Compaction time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "avg(sum without (table_id, table_name) (irate(rocksdb_compaction_times_micros_sum{job=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (irate(rocksdb_compaction_times_micros_count{job=\"$dbcluster\"}[5m]))\r)",
       "legendFormat": "Avg"
      }
     ]
    }
   ]
  }
 ]
}